on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
    build:
      name: Build
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run Trivy vulnerability scanner in repo mode
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'sarif'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL'

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: 'trivy-results.sarif'
          
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # tests:
    #   name: test unitaire
    #   runs-on: ubuntu-latest
    #   steps:
    #     # Checkout the Repo
    #     - uses: actions/checkout@v2

    #     # Install Node 12
    #     - name: Setup Node
    #       uses: actions/setup-node@v1
    #       with:
    #         node-version: 17

    #     # Install dependencies
    #     - run: npm install

    #     # Run tests
    #     - run: npm test